name: Pearlthoughts

on: push

env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@main
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Docker Image
        run: docker build -t notification-app .
      - name: Push Docker image to amazon ecr
        run: |
             docker tag notification-app: latest 055411382616.dkr.ecr.ap-south-1.amazonaws.com/pearlthoughts:notification-app
             docker push 055411382616.dkr.ecr.ap-south-1.amazonaws.com/pearlthoughts:notification-app
