name: Pearlthoughts

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@main
      - name: Build Docker Image
        run: docker build -t notification-app .
